name: WeatherGet
on: [workflow_dispatch]

jobs:
  GetWeather:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
      
      - name: build
        run: dotnet build
        env: 
          API_KEY: ${{ secrets.API_KEY }} 
          
      - name: run
        run: |
          cd weather/bin/Debug/net6.0
          dotnet weather.dll
            

